version: '3.8'

services:
  sitemapper:
    build: .
    container_name: sitemapper-app
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      # Persist extractions between container restarts
      - ./extractions:/app/extractions
      # Optional: Mount for development (comment out for production)
      # - ./:/app
      # - /app/node_modules
    restart: unless-stopped
    networks:
      - sitemapper-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: sitemapper-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - sitemapper
    restart: unless-stopped
    networks:
      - sitemapper-network

networks:
  sitemapper-network:
    driver: bridge

# Optional: Add volume for persistent storage
volumes:
  extractions:
    driver: local