version: '3.8'

services:
  sitemapper:
    build: .
    container_name: sitemapper-pro
    ports:
      - "80:3001"  # Map to port 80 for domain access
    environment:
      - NODE_ENV=production
      - PORT=3001
      - VIRTUAL_HOST=sitemapperpro.local.se
    volumes:
      # Persist extractions between container restarts
      - ./extractions:/app/extractions
      # Optional: Mount for development (comment out for production)
      # - ./:/app
      # - /app/node_modules
    restart: unless-stopped
    networks:
      - sitemapper-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sitemapper.rule=Host(`sitemapperpro.local.se`)"
      - "traefik.http.services.sitemapper.loadbalancer.server.port=3001"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sitemapper-network:
    driver: bridge

# Optional: Add volume for persistent storage
volumes:
  extractions:
    driver: local